//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMDBMovies.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieWriter
    {
        public int ID { get; set; }
        public int WriterID { get; set; }
        public int MovieID { get; set; }
    
        public virtual Movie Movie { get; set; }
        public virtual Writer Writer { get; set; }
    }
}
